#coding: utf8

DEFAULT_SETTINGS_FILENAME = 'settings.ini'
DEFAULT_POSITION_FILENAME = 'result_position.txt'
DEFAULT_ROVER_QUANTITY = 1
DEFAULT_ROVER_UDP_PORT = 5003
DEFAULT_SERVER_UDP_PORT = 60427
DEFAULT_ROVER_ADDRESS = '172.16.2.128'
DEFAULT_TIMER = 100
DEFAULT_TX_DATA = b'30'
DEFAULT_TX_TIMER = 100 # DEFAULT_TIMER = 0,1с
POSITION = '$GNRMC'
LEN_POSITION = 13
LATITUDE_POS = 3
LONGITUDE_POS = 5
SPEED_POS = 7
MODE_POS = 12
DATA_POS = 9
TIME_POS = 1
ALTITUDE = '$GNGGA'
LEN_ALTITUDE = 15
ALTITUDE_MSL_POS = 9
ALTITUDE_DIF_POS = 11
ACCURACY = '$GNGSA'
LEN_ACCURACY = 19
PDOP_POS = 15
HDOP_POS = 16
VDOP_POS = 17
SEPARATOR = '$'
MIN_DELTA_LOAD_URL = 0.000001
DELTA_LONGITUDE_MAP = 0.0008
DELTA_LATITUDE_MAP = 0.0003
DEFAULT_ZOOM = 21

